package com.awb.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.0.2 2016-05-25T14:40:10.385Z
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "FileAttenteVisaService", wsdlLocation = "fileAttenteVisa.wsdl", targetNamespace = "http://ws.server.aida.awb/")
public class FileAttenteVisaService_Service extends Service {

    private final static Logger logger = Logger.getLogger(FileAttenteVisaService_Service.class.getName());

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.server.aida.awb/", "FileAttenteVisaService");
    public final static QName FileAttenteVisaServiceImplPort = new QName("http://ws.server.aida.awb/", "FileAttenteVisaServiceImplPort");

    static {
        URL url = null;
        try {
            url = FileAttenteVisaService_Service.class.getResource("/fileAttenteVisa.wsdl");
            if (url == null)
                throw new MalformedURLException("/fileAttenteVisa.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'fileAttenteVisa.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSDL_LOCATION = url;
    }

    public FileAttenteVisaService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileAttenteVisaService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileAttenteVisaService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return returns FileAttenteVisaService
     */
    @WebEndpoint(name = "FileAttenteVisaServiceImplPort")
    public FileAttenteVisaService getFileAttenteVisaServiceImplPort() {
        return super.getPort(FileAttenteVisaServiceImplPort, FileAttenteVisaService.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
     *            on the proxy. Supported features not in the
     *            <code>features</code> parameter will have their default
     *            values.
     * @return returns FileAttenteVisaService
     */
    @WebEndpoint(name = "FileAttenteVisaServiceImplPort")
    public FileAttenteVisaService getFileAttenteVisaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(FileAttenteVisaServiceImplPort, FileAttenteVisaService.class, features);
    }

}
