package com.awb.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-05-25T14:40:10.355Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://ws.server.aida.awb/", name = "FileAttenteVisaService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FileAttenteVisaService {

    @WebResult(name = "return", targetNamespace = "http://ws.server.aida.awb/", partName = "return")
    @WebMethod
    public ListeOperationsEnAttenteVisaResponse getListeOperationsEnAttenteVisa(
        @WebParam(partName = "arg0", name = "arg0")
        ListeOperationsEnAttenteVisaRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "http://ws.server.aida.awb/", partName = "return")
    @WebMethod
    public SecurityResponse checkAuthentification(
        @WebParam(partName = "arg0", name = "arg0")
        SecurityRequest arg0
    );
}
